import type { MotherboardDataFlow } from '../../types';

export const enBoardFlows: MotherboardDataFlow[] = [
  {
    id: 'flow_cpu_ram',
    name: 'CPU ↔ RAM (Dual-Channel Memory Bus)',
    fromName: 'CPU Integrated Memory Controller (IMC)',
    toName: 'DDR5 DIMM Slots (Slots 2 & 4 / A2 & B2)',
    busType: '128-bit Dual-Channel DDR5 (6000+ MT/s)',
    bandwidth: '~80 - 100 GB/s',
    latency: '~55 - 70 ns (Ultra-Low)',
    color: '#38bdf8',
    svgPath: 'M 310,90 L 345,90',
    directCpu: true,
    purpose: 'Transfers active program instructions, operating system kernel buffers, and live game assets directly into the CPU L3/L2 caches.',
    whyItMatters: 'Daisy-Chain Topology: Motherboard memory traces run directly from the CPU to slot 2 and slot 4 first. Installing RAM in slots 2 and 4 prevents electrical signal reflections from empty stub lines.',
    commonTrap: 'Single-Channel Trap: Installing only 1 memory stick halves your memory bus to 64-bit, severely crippling 1% low framerates and CPU productivity.'
  },
  {
    id: 'flow_cpu_gpu',
    name: 'CPU ↔ Primary GPU (PCIe 5.0/4.0 x16)',
    fromName: 'CPU Direct PCIe Root Complex',
    toName: 'Top PCIe x16 Slot (Graphics Card)',
    busType: '16 Direct High-Speed PCIe Lanes',
    bandwidth: '~64 GB/s (PCIe 4.0) / ~128 GB/s (PCIe 5.0)',
    latency: '< 1 µs (Direct Point-to-Point)',
    color: '#c084fc',
    svgPath: 'M 275,115 L 275,175',
    directCpu: true,
    purpose: 'Streams 3D geometry meshes, vertex buffers, draw commands, and high-resolution textures straight from CPU memory into GPU VRAM.',
    whyItMatters: 'Top Slot Supremacy: The top PCIe slot is the ONLY slot wired directly into the CPU with all 16 physical PCIe lanes. Lower PCIe slots route through the chipset with higher latency and reduced x4/x1 bandwidth.',
    commonTrap: 'Bottom Slot Trap: Placing a gaming GPU into the bottom PCIe slot forces all graphics data through the motherboard chipset, reducing bandwidth by up to 75%!'
  },
  {
    id: 'flow_cpu_m2',
    name: 'CPU ↔ Top M.2 NVMe SSD (PCIe 4.0/5.0 x4)',
    fromName: 'CPU Dedicated Storage Controller',
    toName: 'Top M.2_1 Socket (Under CPU Heatsink)',
    busType: '4 Dedicated Direct PCIe Lanes',
    bandwidth: '~8 GB/s (PCIe 4.0) / ~14 GB/s (PCIe 5.0)',
    latency: '~10 - 20 µs (Direct Storage Access)',
    color: '#facc15',
    svgPath: 'M 265,115 L 265,125',
    directCpu: true,
    purpose: 'Delivers maximum random 4K read/write IOPS and DirectStorage game loading speeds straight into CPU memory without sharing lanes with other devices.',
    whyItMatters: 'OS Boot Drive Priority: Modern CPUs reserve 4 dedicated PCIe lanes specifically for the primary M.2 slot. Always install Windows or your primary OS drive here for the fastest responsiveness.',
    commonTrap: 'Missing Heatsink Throttling: High-speed Gen 4 and Gen 5 NVMe drives quickly exceed 75°C under load. Never operate the top M.2 SSD without its motherboard thermal heatsink.'
  },
  {
    id: 'flow_cpu_chipset',
    name: 'CPU ↔ Chipset (DMI Highway Interconnect)',
    fromName: 'CPU High-Speed I/O Hub',
    toName: 'Motherboard Chipset (PCH / Southbridge)',
    busType: 'DMI 4.0 x8 (Intel) / PCIe 4.0 x4 (AMD)',
    bandwidth: '~15.75 GB/s (High-Speed Trunk Link)',
    latency: '~50 - 100 ns (Intermediate Hub Transit)',
    color: '#10b981',
    svgPath: 'M 305,115 C 340,150 435,185 460,235',
    directCpu: false,
    purpose: 'Acts as the central communication trunk line carrying all secondary traffic (SATA drives, Wi-Fi, Ethernet, USB ports, secondary M.2 slots) to the CPU.',
    whyItMatters: 'The Traffic Director: Without the chipset, the CPU would need 3,000+ pins to connect every peripheral. The chipset aggregates dozens of slower peripherals into one efficient highway.',
    commonTrap: 'DMI Bus Bottleneck: If you transfer data between two chipset-connected M.2 SSDs while downloading at 10Gbps, all devices compete for this single DMI bandwidth pipe.'
  },
  {
    id: 'flow_chipset_lan',
    name: 'Chipset ↔ 2.5GbE Network Controller (PCIe x1 LAN PHY)',
    fromName: 'Motherboard Chipset (via DMI Highway)',
    toName: '2.5GbE Ethernet Controller IC & Rear RJ-45 Port',
    busType: 'PCIe 3.0/4.0 x1 Bus (Internal PCB Differential Pairs)',
    bandwidth: '2.5 Gbps (~312.5 MB/s Full Duplex)',
    latency: '< 0.1 ms (Hardware Packet Processing)',
    color: '#10b981',
    svgPath: 'M 445,260 L 210,260 C 185,260 175,260 158,260',
    directCpu: false,
    purpose: 'Transfers incoming and outgoing Gigabit/2.5G network packets between the physical RJ-45 jack and the chipset, routing traffic straight to RAM via Direct Memory Access (DMA).',
    whyItMatters: 'Silicon Packet Offloading: The dedicated network controller IC performs TCP/IP checksum calculation and packet filtering in silicon, offloading networking completely from CPU cores.',
    commonTrap: 'Missing Driver Trap: Fresh Windows installations often do not include modern 2.5GbE drivers (e.g., Intel I225-V or Realtek RTL8125). Keep the motherboard LAN driver on a USB drive before installing your OS!'
  },
  {
    id: 'flow_chipset_wifi_bt',
    name: 'Chipset ↔ Wi-Fi 6E/7 & Bluetooth Module (M.2 Key-E: PCIe + USB)',
    fromName: 'Motherboard Chipset (PCH)',
    toName: 'Wi-Fi 6E/7 & Bluetooth M.2 Key-E Module (Rear I/O)',
    busType: 'Hybrid: PCIe x1 (Wi-Fi) + Internal USB 2.0 (Bluetooth)',
    bandwidth: '2.4 - 5.8 Gbps (Wi-Fi 6E/7) + 480 Mbps (Bluetooth 5.3/5.4)',
    latency: '~2 - 4 ms (Air link + bus latency)',
    color: '#06b6d4',
    svgPath: 'M 460,235 C 430,170 230,140 155,140',
    directCpu: false,
    purpose: 'Powers the motherboard dual-band wireless card: High-bandwidth Wi-Fi communicates over a PCIe x1 lane, while low-latency Bluetooth (mice, keyboards, audio) runs over an internal USB 2.0 bus inside the exact same M.2 Key-E slot.',
    whyItMatters: 'Single Slot, Dual Protocols: Motherboard Key-E slots provide both PCIe and USB signals on one card. If you use a desktop PCIe Wi-Fi expansion card on older boards, you must connect an extra small cable from the card to an internal motherboard USB 2.0 header to activate Bluetooth!',
    commonTrap: 'Missing Antenna Cage Trap: Without the external antenna screwed onto the rear gold RP-SMA ports, the steel PC case acts as a Faraday cage—Bluetooth will cut out at 1 meter and Wi-Fi speeds drop by 99%!'
  },
  {
    id: 'flow_chipset_sata',
    name: 'Chipset ↔ SATA Drives & Secondary Storage',
    fromName: 'Motherboard Chipset (PCH)',
    toName: 'SATA 6Gbps Ports & Lower M.2 Slots',
    busType: 'SATA 3.0 (AHCI 6Gbps) / Chipset PCIe Gen 4',
    bandwidth: '600 MB/s (per SATA port) / ~8 GB/s (Secondary M.2)',
    latency: '~50 - 150 µs',
    color: '#f97316',
    svgPath: 'M 515,252 L 560,252',
    directCpu: false,
    purpose: 'Manages secondary bulk storage drives, 2.5" SATA SSDs, and legacy 3.5" spinning hard drives.',
    whyItMatters: 'Lane Sharing Rules: Because chipset lanes are shared, plugging an M.2 drive into slot M2_2 on some boards automatically disables SATA ports 5 and 6.',
    commonTrap: 'Disabled Port Confusion: If a newly connected SATA hard drive does not show up in BIOS, check if a secondary M.2 SSD has disabled that specific SATA port!'
  },
  {
    id: 'flow_chipset_io',
    name: 'Chipset ↔ Front USB 3.0 & HD Audio Codec',
    fromName: 'Motherboard Chipset (PCH)',
    toName: 'Front Panel USB 3.0 Header & HD Audio Codec (AAFP)',
    busType: 'USB 3.2 Gen 1/Gen 2 + HD Audio Link (Azalia)',
    bandwidth: '5 - 20 Gbps (USB) / 192 kHz 24-bit Audio',
    latency: '~100 - 500 µs',
    color: '#ec4899',
    svgPath: 'M 480,283 C 440,310 230,315 177,325',
    directCpu: false,
    purpose: 'Handles chassis front-panel USB transfers, webcam streaming, and digital-to-analog sound conversion via dedicated PCB-isolated audio capacitors.',
    whyItMatters: 'CPU Isolation: Offloading low-speed peripheral interrupts to the chipset ensures the CPU compute cores remain 100% focused on frame rendering and application workloads.',
    commonTrap: 'Audio Cable Interference: Routing the front panel HD Audio cable parallel to high-current PSU cables creates electromagnetic buzzing and static in analog headphones.'
  }
];
