import type { MotherboardDataFlow } from '../../types';

export const zhBoardFlows: MotherboardDataFlow[] = [
  {
    id: 'flow_cpu_ram',
    name: 'CPU ↔ RAM（雙通道高速記憶體匯流排）',
    fromName: 'CPU 整合式記憶體控制器 (IMC)',
    toName: 'DDR5 DIMM 插槽（推薦插第 2 與 4 槽 / A2 & B2）',
    busType: '128-bit 雙通道 DDR5 (6000+ MT/s)',
    bandwidth: '~80 - 100 GB/s',
    latency: '~55 - 70 ns (極致超低延遲)',
    color: '#38bdf8',
    svgPath: 'M 310,90 L 345,90',
    directCpu: true,
    purpose: '將正在執行的程式指令、遊戲場景資源與作業系統核心資料，以極快速度載入 CPU L3/L2 快取記憶體。',
    whyItMatters: '菊花鏈 (Daisy-Chain) 走線原則：現代主機板記憶體線路優先通往第 2 與第 4 槽。將記憶體插在 2/4 槽能消除空腳殘線的電氣訊號反射，確保高頻 XMP/EXPO 穩定不藍屏。',
    commonTrap: '單通道巨大效能陷阱：若只插 1 條記憶體，頻寬將腰斬至 64-bit，導致 3A 遊戲 1% Low 幀率暴跌與頻繁掉幀卡頓。'
  },
  {
    id: 'flow_cpu_gpu',
    name: 'CPU ↔ 主顯示卡（PCIe 5.0/4.0 x16 直連通道）',
    fromName: 'CPU 內部 PCIe 根複合體 (Root Complex)',
    toName: '第一槽 PCIe x16 金屬加固插槽 (顯示卡)',
    busType: '16 條專屬實體高速 PCIe 差分通道',
    bandwidth: '~64 GB/s (PCIe 4.0) / ~128 GB/s (PCIe 5.0)',
    latency: '< 1 µs (點對點極速直連)',
    color: '#c084fc',
    svgPath: 'M 275,115 L 275,175',
    directCpu: true,
    purpose: '以極低延遲將 3D 幾何模型頂點資料、繪圖呼叫指令 (Draw Calls) 與高解析度貼圖從主記憶體倒進顯示卡 VRAM 顯存。',
    whyItMatters: '第一槽絕對定律：頂部第一條 PCIe 插槽是全主機板「唯一」由 CPU 內部直出 16 條通道的插槽！下方其他 PCIe 插槽均繞經晶片組轉發，頻寬僅 x4 或 x1 且延遲大幅增加。',
    commonTrap: '插錯下方插槽翻車：將高階遊戲顯示卡插在主機板下方副插槽，傳輸頻寬將暴跌高達 75%，大幅削弱顯卡效能！'
  },
  {
    id: 'flow_cpu_m2',
    name: 'CPU ↔ 第一槽 M.2 NVMe SSD（PCIe 4.0/5.0 x4 直連）',
    fromName: 'CPU 專用儲存 PCIe 控制器',
    toName: '第一槽 M.2_1 插槽（CPU 散熱片正下方）',
    busType: '4 條專屬獨立 PCIe 4.0/5.0 傳輸通道',
    bandwidth: '~8 GB/s (PCIe 4.0) / ~14 GB/s (PCIe 5.0)',
    latency: '~10 - 20 µs (極速磁碟存取)',
    color: '#facc15',
    svgPath: 'M 265,115 L 265,125',
    directCpu: true,
    purpose: '提供最強 4K 隨機讀寫 IOPS 與 DirectStorage 遊戲秒速載入體驗，資料完全不與其他周邊裝置爭搶頻寬。',
    whyItMatters: '系統開機碟第一順位：現代 CPU 特意預留 4 條獨立 PCIe 通道直達第一槽 M.2。作業系統 Windows 碟務必安裝在此槽以獲取極致開機與反應速度。',
    commonTrap: '未裝散熱片過熱降速：高速 PCIe Gen 4/Gen 5 固態硬碟在高速讀寫時溫度極易飆破 75°C。切勿裸碟運作，務必蓋上主機板金屬散熱盔甲。'
  },
  {
    id: 'flow_cpu_chipset',
    name: 'CPU ↔ 晶片組（DMI 4.0 高速骨幹公路）',
    fromName: 'CPU 高速 I/O 整合中心',
    toName: '主機板晶片組 (PCH / 南橋晶片)',
    busType: 'DMI 4.0 x8 (Intel) / PCIe 4.0 x4 (AMD)',
    bandwidth: '~15.75 GB/s (主幹高吞吐匯流排)',
    latency: '~50 - 100 ns (中繼轉發延遲)',
    color: '#10b981',
    svgPath: 'M 305,115 C 340,150 435,185 460,235',
    directCpu: false,
    purpose: '充當全機周邊樞紐的中央骨幹大道，將 SATA 硬碟、Wi-Fi、有線網路、USB 連接埠與副 M.2 流量彙整傳輸給 CPU。',
    whyItMatters: '交通指揮調度中心：若無晶片組，CPU 將需要超過 3000 根針腳才能接通每個 USB 與硬碟。晶片組將數十個周邊整合為一條精簡高速的高速公路。',
    commonTrap: 'DMI 匯流排塞車瓶頸：若你同時在兩個接於晶片組的 SSD 間互傳大檔、同時進行萬兆網路下載，所有流量都會在此 DMI 骨幹上互相競爭頻寬。'
  },
  {
    id: 'flow_chipset_lan',
    name: '晶片組 ↔ 2.5GbE 網路控制晶片 (PCIe x1 LAN PHY)',
    fromName: '主機板晶片組 (經由 DMI 總線骨幹)',
    toName: '2.5GbE 網路控制器晶片 (PHY/MAC IC) 與後置 RJ-45 網埠',
    busType: 'PCIe 3.0/4.0 x1 差分通道 (板載差分阻抗訊號線)',
    bandwidth: '2.5 Gbps 全雙工 (~312.5 MB/s 實際頻寬)',
    latency: '< 0.1 ms (硬體級極速封包處理)',
    color: '#10b981',
    svgPath: 'M 445,260 L 210,260 C 185,260 175,260 158,260',
    directCpu: false,
    purpose: '將來自 RJ-45 實體網孔的網路封包，經由隔離變壓器送入專用網卡晶片，透過 PCIe x1 通道送交晶片組，並經由 DMI 骨幹以 DMA (直接記憶體存取) 方式注入系統記憶體。',
    whyItMatters: '硬體級封包卸載 (Offloading)：專用網卡晶片具備獨立硬體校驗和 (Checksum Offload) 與中斷節流技術，確保 2.5G 全速下載或高頻低延遲遊戲對戰時，完全不耗損 CPU 運算核心效能。',
    commonTrap: '驅動缺失斷網陷阱：全新安裝 Windows 系統時，微軟官方映像檔常未內建最新的 2.5G 網卡驅動（如 Intel I225-V 或 Realtek 8125），導致開機無網路無法登入微軟帳號。組裝前建議先用隨身碟備好主機板官網網卡驅動。'
  },
  {
    id: 'flow_chipset_wifi_bt',
    name: '晶片組 ↔ Wi-Fi 6E/7 & 藍牙整合模組 (M.2 Key-E: PCIe + USB)',
    fromName: '主機板晶片組 (PCH)',
    toName: 'Wi-Fi 6E/7 & 藍牙 M.2 Key-E 模組 (後置 I/O 遮罩內)',
    busType: '混合雙總線：PCIe x1 (Wi-Fi 6E/7) + 板載 USB 2.0 (藍牙 5.3/5.4)',
    bandwidth: '2.4 - 5.8 Gbps (Wi-Fi 6E/7) + 480 Mbps (藍牙 5.3/5.4)',
    latency: '~2 - 4 ms (空口無線傳輸與總線轉換延遲)',
    color: '#06b6d4',
    svgPath: 'M 460,235 C 430,170 230,140 155,140',
    directCpu: false,
    purpose: '驅動主機板的一體式無線網卡：數 Gbps 級的高速 Wi-Fi 走晶片組 PCIe x1 通道；而低功耗、低延遲的藍牙耳機、鍵盤滑鼠則共用該卡座中的板載 USB 2.0 訊號線！',
    whyItMatters: '一槽雙用・雙重協定：主機板 Key-E 插槽同時鋪設了 PCIe 與 USB 雙通訊接腳。這就是為什麼若在舊電腦擴充 PCIe Wi-Fi 介面卡時，除了插在插槽上，還必須額外拉一條小黑線插在主機板的 USB 2.0 排針上，藍牙才能運作！',
    commonTrap: '機殼屏蔽天線陷阱：若未將外部雙頻天線鎖在後置鍍金 RP-SMA 孔上，金屬機殼會形成法拉第籠徹底屏蔽無線電波，導致藍牙離開 1 公尺就爆音斷線、Wi-Fi 訊號只剩 1 格！'
  },
  {
    id: 'flow_chipset_sata',
    name: '晶片組 ↔ SATA 硬碟與副儲存插槽',
    fromName: '主機板晶片組 (PCH)',
    toName: 'SATA 6Gbps 排針插座與副 M.2 插槽',
    busType: 'SATA 3.0 (AHCI 6Gbps) / 晶片組 PCIe 通道',
    bandwidth: '600 MB/s (每組 SATA) / ~8 GB/s (副 M.2)',
    latency: '~50 - 150 µs',
    color: '#f97316',
    svgPath: 'M 515,252 L 560,252',
    directCpu: false,
    purpose: '調度傳統機械硬碟 (HDD)、2.5 吋 SATA 固態硬碟，以及容量擴充用之副儲存設備。',
    whyItMatters: '通道共用互斥條款：晶片組高速通道有限，在部分主機板上，當你插上第二條 M.2 SSD 時，主機板會自動關閉 SATA 5 與 6 號插座。',
    commonTrap: '硬碟無故消失之謎：若新裝的 SATA 硬碟在 BIOS 中完全讀不到，請查閱說明書確認是否被副 M.2 插槽停用了該 SATA 插座！'
  },
  {
    id: 'flow_chipset_io',
    name: '晶片組 ↔ 前置 USB 3.0 與 HD Audio 音效晶片',
    fromName: '主機板晶片組 (PCH)',
    toName: '前置 USB 3.0 排針座與獨立 HD Audio 音效電路 (AAFP)',
    busType: 'USB 3.2 Gen 1/Gen 2 + HD Audio 總線 (Azalia)',
    bandwidth: '5 - 20 Gbps (USB) / 192 kHz 24-bit 高解析音訊',
    latency: '~100 - 500 µs',
    color: '#ec4899',
    svgPath: 'M 480,283 C 440,310 230,315 177,325',
    directCpu: false,
    purpose: '調度機殼前置 USB 隨身碟傳輸、視訊鏡頭串流，並經由主機板音效隔離區的 DAC 解碼晶片將數位音訊轉為 3.5mm 類比耳機純淨訊號。',
    whyItMatters: '保護 CPU 運算資源：將慢速周邊的中斷請求 (Interrupts) 交給晶片組處理，確保 CPU 核心能 100% 全力專注於遊戲幀數運算與複雜工作。',
    commonTrap: '音效排線電磁干擾：若將前面板音效線與大電流電源線緊貼綑綁，耳機很容易聽見惱人的高頻電磁底噪與滋滋聲。'
  }
];
